package com.example.myapplication1.data.model

import com.example.myapplication1.R

data class Station(
    val key: String,
    val nameRes: Int,
    val zoneRes: List<Int>   // most stations: one entry; boundary stations: two
)

data class LineStationEntry(
    val lineKey: String,
    val stationKey: String
)

val lineStationEntries = listOf(

    // V
    LineStationEntry("victoria", "blackhorse_road"),
    LineStationEntry("victoria", "brixton"),
    LineStationEntry("victoria", "green_park"),
    LineStationEntry("victoria", "euston"),
    LineStationEntry("victoria", "finsbury_park"),
    LineStationEntry("victoria", "highbury_and_islington"),
    LineStationEntry("victoria", "kings_cross_st_pancras"),
    LineStationEntry("victoria", "oxford_circus"),
    LineStationEntry("victoria", "pimlico"),
    LineStationEntry("victoria", "seven_sisters"),
    LineStationEntry("victoria", "stockwell"),
    LineStationEntry("victoria", "tottenham_hale"),
    LineStationEntry("victoria", "vauxhall"),
    LineStationEntry("victoria", "victoria"),
    LineStationEntry("victoria", "walthamstow_central"),
    LineStationEntry("victoria", "warren_street"),
    // ... other lines' entries go here as you build them out
)

fun stationsForLine(lineKey: String): List<Station> {
    val stationByKey = allStations.associateBy { it.key }
    return lineStationEntries
        .filter { it.lineKey == lineKey }
        .mapNotNull { stationByKey[it.stationKey] }
}

val allStations = listOf(
    // A (20)
    Station("abbey_road", R.string.station_abbey_road, listOf(R.string.zone_2, R.string.zone_3)),
    Station("abbey_wood", R.string.station_abbey_wood, listOf(R.string.zone_4)),
    Station("acton_central", R.string.station_acton_central, listOf(R.string.zone_3)),
    Station("acton_main_line", R.string.station_acton_main_line, listOf(R.string.zone_3)),
    Station("acton_town", R.string.station_acton_town, listOf(R.string.zone_3)),
    Station("addington_village", R.string.station_addington_village, listOf(R.string.zone_special)),
    Station("addiscombe", R.string.station_addiscombe, listOf(R.string.zone_special)),
    Station("aldgate", R.string.station_aldgate, listOf(R.string.zone_1)),
    Station("aldgate_east", R.string.station_aldgate_east, listOf(R.string.zone_1)),
    Station("all_saints", R.string.station_all_saints, listOf(R.string.zone_2)),
    Station("alperton", R.string.station_alperton, listOf(R.string.zone_4)),
    Station("amersham", R.string.station_amersham, listOf(R.string.zone_9)),
    Station("ampere_way", R.string.station_ampere_way, listOf(R.string.zone_special)),
    Station("anerley", R.string.station_anerley, listOf(R.string.zone_4)),
    Station("angel", R.string.station_angel, listOf(R.string.zone_1)),
    Station("archway", R.string.station_archway, listOf(R.string.zone_2, R.string.zone_3)),
    Station("arena", R.string.station_arena, listOf(R.string.zone_special)),
    Station("arnos_grove", R.string.station_arnos_grove, listOf(R.string.zone_4)),
    Station("arsenal", R.string.station_arsenal, listOf(R.string.zone_2)),
    Station("avenue_road", R.string.station_avenue_road, listOf(R.string.zone_special)),

    // B (44)
    Station("baker_street", R.string.station_baker_street, listOf(R.string.zone_1)),
    Station("balham", R.string.station_balham, listOf(R.string.zone_3)),
    Station("bank", R.string.station_bank, listOf(R.string.zone_1)),
    Station("barbican", R.string.station_barbican, listOf(R.string.zone_1)),
    Station("barking", R.string.station_barking, listOf(R.string.zone_4)),
    Station("barking_riverside", R.string.station_barking_riverside, listOf(R.string.zone_4)),
    Station("barkingside", R.string.station_barkingside, listOf(R.string.zone_4)),
    Station("barons_court", R.string.station_barons_court, listOf(R.string.zone_2)),
    Station("battersea_power_station", R.string.station_battersea_power_station, listOf(R.string.zone_2)),
    Station("bayswater", R.string.station_bayswater, listOf(R.string.zone_1)),
    Station("beckenham_junction", R.string.station_beckenham_junction, listOf(R.string.zone_special)),
    Station("beckenham_road", R.string.station_beckenham_road, listOf(R.string.zone_special)),
    Station("beckton", R.string.station_beckton, listOf(R.string.zone_3)),
    Station("beckton_park", R.string.station_beckton_park, listOf(R.string.zone_3)),
    Station("becontree", R.string.station_becontree, listOf(R.string.zone_5)),
    Station("beddington_lane", R.string.station_,beddington_lane listOf(R.string.zone_special)),
    Station("belgrave_walk", R.string.station_belgrave_walk, listOf(R.string.zone_special)),
    Station("belsize_park", R.string.station_belsize_park, listOf(R.string.zone_2)),
    Station("bermondsey", R.string.station_bermondsey, listOf(R.string.zone_2)),
    Station("bethnal_green", R.string.station_bethnal_green, listOf(R.string.zone_2)),
    Station("birkbeck", R.string.station_birkbeck, listOf(R.string.zone_special)),
    Station("blackfriars", R.string.station_blackfriars, listOf(R.string.zone_1)),
    Station("blackhorse_lane", R.string.station_blackhorse_lane, listOf(R.string.zone_3)),
    Station("blackhorse_road", R.string.station_blackhorse_road, listOf(R.string.zone_3)),
    Station("blackwall", R.string.station_blackwall, listOf(R.string.zone_2)),
    Station("bond_street", R.string.station_bond_street, listOf(R.string.zone_1)),
    Station("borough", R.string.station_borough, listOf(R.string.zone_1)),
    Station("boston_manor", R.string.station_boston_manor, listOf(R.string.zone_4)),
    Station("bounds_green", R.string.station_bounds_green, listOf(R.string.zone_3,R.string.zone_4)),
    Station("bow_church", R.string.station_bow_church, listOf(R.string.zone_2)),
    Station("bow_road", R.string.station_bow_road, listOf(R.string.zone_2)),
    Station("brent_cross", R.string.station_brent_cross, listOf(R.string.zone_3)),
    Station("brentwood", R.string.station_brentwood, listOf(R.string.zone_9)),
    Station("brixton", R.string.station_brixton, listOf(R.string.zone_2)),
    Station("brockley", R.string.station_brockley, listOf(R.string.zone_2)),
    Station("bromley_by_bow", R.string.station_bromley_by_bow, listOf(R.string.zone_2,R.string.zone_3)),
    Station("brondesbury", R.string.station_brondesbury, listOf(R.string.zone_2)),
    Station("brondesbury_park", R.string.station_brondesbury_park, listOf(R.string.zone_2)),
    Station("bruce_grove", R.string.station_bruce_grove, listOf(R.string.zone_3)),
    Station("buckhurst_hill", R.string.station_buckhurst_hill, listOf(R.string.zone_5)),
    Station("burnham", R.string.station_burnham, listOf(R.string.zone_special)),
    Station("burnt_oak", R.string.station_burnt_oak, listOf(R.string.zone_4)),
    Station("bush_hill_park", R.string.station_bush_hill_park, listOf(R.string.zone_5)),
    Station("bushey", R.string.station_bushey, listOf(R.string.zone_8)),

    // C (42)
    Station("caledonian_road", R.string.station_caledonian_road, listOf(R.string.zone_2)),
    Station("caledonian_road_and_barnsbury", R.string.station_caledonian_road_and_barnsbury, listOf(R.string.zone_2)),
    Station("cambridge_heath", R.string.station_cambridge_heath, listOf(R.string.zone_2)),
    Station("camden_road", R.string.station_camden_road, listOf(R.string.zone_2)),
    Station("camden_town", R.string.station_camden_town, listOf(R.string.zone_2)),
    Station("canada_water", R.string.station_canada_water, listOf(R.string.zone_2)),
    Station("canary_wharf", R.string.station_canary_wharf, listOf(R.string.zone_2)),
    Station("canning_town", R.string.station_canning_town, listOf(R.string.zone_2,R.string.zone_3)),
    Station("cannon_street", R.string.station_cannon_street, listOf(R.string.zone_1)),
    Station("canonbury", R.string.station_canonbury, listOf(R.string.zone_2)),
    Station("canons_park", R.string.station_canons_park, listOf(R.string.zone_5)),
    Station("carpenders_park", R.string.station_carpenders_park, listOf(R.string.zone_7)),
    Station("centrale", R.string.station_centrale, listOf(R.string.zone_special)),
    Station("chadwell_heath", R.string.station_chadwell_heath, listOf(R.string.zone_5)),
    Station("chalfont_and_latimer", R.string.station_chalfont_and_latimer, listOf(R.string.zone_8)),
    Station("chalk_farm", R.string.station_chalk_farm, listOf(R.string.zone_2)),
    Station("chancery_lane", R.string.station_chancery_lane, listOf(R.string.zone_1)),
    Station("charing_cross", R.string.station_charing_cross, listOf(R.string.zone_1)),
    Station("chesham", R.string.station_chesham, listOf(R.string.zone_9)),
    Station("cheshunt", R.string.station_cheshunt, listOf(R.string.zone_8)),
    Station("chigwell", R.string.station_chingford, listOf(R.string.zone_5)),
    Station("chiswick_park", R.string.station_chiswick_park, listOf(R.string.zone_3)),
    Station("chorleywood", R.string.station_chorleywood, listOf(R.string.zone_7)),
    Station("church_street", R.string.station_church_street, listOf(R.string.zone_special)),
    Station("clapham_common", R.string.station_clapham_common, listOf(R.string.zone_2)),
    Station("clapham_high_street", R.string.station_clapham_high_street, listOf(R.string.zone_2)),
    Station("clapham_junction", R.string.station_clapham_junction, listOf(R.string.zone_2)),
    Station("clapham_north", R.string.station_clapham_north, listOf(R.string.zone_2)),
    Station("clapham_south", R.string.station_clapham_south, listOf(R.string.zone_2, R.string.zone_3)),
    Station("clapton", R.string.station_clapton, listOf(R.string.zone_2, R.string.zone_3)),
    Station("cockfosters", R.string.station_cockfosters, listOf(R.string.zone_5)),
    Station("colindale", R.string.station_colindale, listOf(R.string.zone_4)),
    Station("colliers_wood", R.string.station_colliers_wood, listOf(R.string.zone_3)),
    Station("coombe_lane", R.string.station_coombe_lane, listOf(R.string.zone_special)),
    Station("covent_garden", R.string.station_covent_garden, listOf(R.string.zone_1)),
    Station("crossharbour", R.string.station_crossharbour, listOf(R.string.zone_2)),
    Station("crouch_hill", R.string.station_crouch_hill, listOf(R.string.zone_3)),
    Station("croxley", R.string.station_croxley, listOf(R.string.zone_7)),
    Station("crystal_palace", R.string.station_crystal_palace, listOf(R.string.zone_3, R.string.zone_4)),
    Station("custom_house", R.string.station_custom_house, listOf(R.string.zone_3)),
    Station("cutty_sark", R.string.station_cutty_sark, listOf(R.string.zone_2, R.string.zone_3)),
    Station("cyprus", R.string.station_cyprus, listOf(R.string.zone_3)),

    // D ()
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // E ()
    Station("euston", R.string.station_euston, listOf(R.string.zone_1)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // F ()
    Station("finsbury_park", R.string.station_finsbury_park, listOf(R.string.zone_2)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // G ()
    Station("green_park", R.string. R.string.station_green_park, listOf(R.string.zone_1)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // H ()
    Station("highbury_and_islington", R.string. R.string.station_highbury_and_islington, listOf(R.string.zone_2)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // I (5)
    Station("ickenham", R.string. ,listOf(R.string.station_ickenham)
    Station("ilford", R.string. ,listOf(R.string.station_ilford)
    Station("imperial_wharf", R.string. ,listOf(R.string.station_imperial_wharf)
    Station("island_gardens", R.string. ,listOf(R.string.station_island_gardens)
    Station("iver", R.string. ,listOf(R.string.station_iver)

    // K ()
    Station("kings_cross_st_pancras", R.string.station_kings_cross_st_pancras, listOf(R.string.zone_1)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // L ()
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // M ()
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // N
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // O 
    Station("oxford_circus", R.string.station_oxford_circus, listOf(R.string.zone_1)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // P
    Station("pimlico", R.string.station_pimlico, listOf(R.string.zone_1)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // Q
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // R (20)
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // S
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("seven_sisters", R.string.station_seven_sisters, listOf(R.string.zone_3)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("stockwell", R.string.station_stockwell, listOf(R.string.zone_2)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // T
    Station("tottenham_hale", R.string.station_tottenham_hale, listOf(R.string.zone_3)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),

    // U (6)
    Station("upminster", R.string. ,listOf(R.string.station_upminster)),
    Station("upminster_bridge", R.string. ,listOf(R.string.station_upminster_bridge)),
    Station("upney", R.string. ,listOf(R.string.station_upney)),
    Station("upper_holloway", R.string. ,listOf(R.string.station_upper_holloway)),
    Station("upton_park", R.string. ,listOf(R.string.station_upton_park)),
    Station("uxbridge", R.string. ,listOf(R.string.station_uxbridge)),

    // V (2)
    Station("vauxhall", R.string.station_vauxhall, listOf(R.string.zone_1, R.string.zone_2)),
    Station("victoria", R.string.station_victoria, listOf(R.string.zone_1)),

    // W ()
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("walthamstow_central", R.string.station_walthamstow_central, listOf(R.string.zone_3)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("warren_street", R.string.station_warren_street, listOf(R.string.zone_1)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_)),
    Station("", R.string.station_, listOf(R.string.zone_))
    )
