package com.example.myapplication1.data.model

import com.example.myapplication1.R

data class Station(
    val key: String,
    val nameRes: Int,
    val zoneRes: List<Int>   // most stations: one entry; boundary stations: two
)

data class LineStationEntry(
    val lineKey: String,
    val stationKey: String
)

val lineStationEntries = listOf(
    // B
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),
    LineStationEntry("bakerloo", ""),

    // Ce
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),
    LineStationEntry("central", ""),

    // Ci
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),
    LineStationEntry("circle", ""),

    // D
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),
    LineStationEntry("district", ""),

    // H
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),
    LineStationEntry("hammersmith_and_city", ""),

    // J
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),
    LineStationEntry("jubilee", ""),

    // M
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),
    LineStationEntry("metropolitan", ""),

    // N
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),
    LineStationEntry("northern", ""),

    // P
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),
    LineStationEntry("piccadilly", ""),

    // V
    LineStationEntry("victoria", "blackhorse_road"),
    LineStationEntry("victoria", "brixton"),
    LineStationEntry("victoria", "green_park"),
    LineStationEntry("victoria", "euston"),
    LineStationEntry("victoria", "finsbury_park"),
    LineStationEntry("victoria", "highbury_and_islington"),
    LineStationEntry("victoria", "kings_cross_st_pancras"),
    LineStationEntry("victoria", "oxford_circus"),
    LineStationEntry("victoria", "pimlico"),
    LineStationEntry("victoria", "seven_sisters"),
    LineStationEntry("victoria", "stockwell"),
    LineStationEntry("victoria", "tottenham_hale"),
    LineStationEntry("victoria", "vauxhall"),
    LineStationEntry("victoria", "victoria"),
    LineStationEntry("victoria", "walthamstow_central"),
    LineStationEntry("victoria", "warren_street"),

    // W
    LineStationEntry("waterloo_and_city", ""),
    LineStationEntry("waterloo_and_city", ""),


    // DLR
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),
    LineStationEntry("dlr", ""),

    // E
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),
    LineStationEntry("elizabeth", ""),

    // Lib
    LineStationEntry("liberty", ""),
    LineStationEntry("liberty", ""),

    // Lio
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),
    LineStationEntry("lioness", ""),

    // S
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),
    LineStationEntry("suffragette", ""),

    // We
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),
    LineStationEntry("weaver", ""),

    // Wi
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),
    LineStationEntry("windrush", ""),

    // T
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),
    LineStationEntry("tram", ""),

    // Ca
    LineStationEntry("cable_car", ""),
    LineStationEntry("cable_car", ""),

    // ... other lines' entries go here as you build them out
)

fun stationsForLine(lineKey: String): List<Station> {
    val stationByKey = allStations.associateBy { it.key }
    return lineStationEntries
        .filter { it.lineKey == lineKey }
        .mapNotNull { stationByKey[it.stationKey] }
}

val allStations = listOf(
    // A (20)
    Station("abbey_road", R.string.station_abbey_road, listOf(R.string.zone_2, R.string.zone_3)),
    Station("abbey_wood", R.string.station_abbey_wood, listOf(R.string.zone_4)),
    Station("acton_central", R.string.station_acton_central, listOf(R.string.zone_3)),
    Station("acton_main_line", R.string.station_acton_main_line, listOf(R.string.zone_3)),
    Station("acton_town", R.string.station_acton_town, listOf(R.string.zone_3)),
    Station("addington_village", R.string.station_addington_village, listOf(R.string.zone_special)),
    Station("addiscombe", R.string.station_addiscombe, listOf(R.string.zone_special)),
    Station("aldgate", R.string.station_aldgate, listOf(R.string.zone_1)),
    Station("aldgate_east", R.string.station_aldgate_east, listOf(R.string.zone_1)),
    Station("all_saints", R.string.station_all_saints, listOf(R.string.zone_2)),
    Station("alperton", R.string.station_alperton, listOf(R.string.zone_4)),
    Station("amersham", R.string.station_amersham, listOf(R.string.zone_9)),
    Station("ampere_way", R.string.station_ampere_way, listOf(R.string.zone_special)),
    Station("anerley", R.string.station_anerley, listOf(R.string.zone_4)),
    Station("angel", R.string.station_angel, listOf(R.string.zone_1)),
    Station("archway", R.string.station_archway, listOf(R.string.zone_2, R.string.zone_3)),
    Station("arena", R.string.station_arena, listOf(R.string.zone_special)),
    Station("arnos_grove", R.string.station_arnos_grove, listOf(R.string.zone_4)),
    Station("arsenal", R.string.station_arsenal, listOf(R.string.zone_2)),
    Station("avenue_road", R.string.station_avenue_road, listOf(R.string.zone_special)),

    // B (44)
    Station("baker_street", R.string.station_baker_street, listOf(R.string.zone_1)),
    Station("balham", R.string.station_balham, listOf(R.string.zone_3)),
    Station("bank", R.string.station_bank, listOf(R.string.zone_1)),
    Station("barbican", R.string.station_barbican, listOf(R.string.zone_1)),
    Station("barking", R.string.station_barking, listOf(R.string.zone_4)),
    Station("barking_riverside", R.string.station_barking_riverside, listOf(R.string.zone_4)),
    Station("barkingside", R.string.station_barkingside, listOf(R.string.zone_4)),
    Station("barons_court", R.string.station_barons_court, listOf(R.string.zone_2)),
    Station("battersea_power_station", R.string.station_battersea_power_station, listOf(R.string.zone_2)),
    Station("bayswater", R.string.station_bayswater, listOf(R.string.zone_1)),
    Station("beckenham_junction", R.string.station_beckenham_junction, listOf(R.string.zone_special)),
    Station("beckenham_road", R.string.station_beckenham_road, listOf(R.string.zone_special)),
    Station("beckton", R.string.station_beckton, listOf(R.string.zone_3)),
    Station("beckton_park", R.string.station_beckton_park, listOf(R.string.zone_3)),
    Station("becontree", R.string.station_becontree, listOf(R.string.zone_5)),
    Station("beddington_lane", R.string.station_beddington_lane, listOf(R.string.zone_special)),
    Station("belgrave_walk", R.string.station_belgrave_walk, listOf(R.string.zone_special)),
    Station("belsize_park", R.string.station_belsize_park, listOf(R.string.zone_2)),
    Station("bermondsey", R.string.station_bermondsey, listOf(R.string.zone_2)),
    Station("bethnal_green", R.string.station_bethnal_green, listOf(R.string.zone_2)),
    Station("birkbeck", R.string.station_birkbeck, listOf(R.string.zone_special)),
    Station("blackfriars", R.string.station_blackfriars, listOf(R.string.zone_1)),
    Station("blackhorse_lane", R.string.station_blackhorse_lane, listOf(R.string.zone_3)),
    Station("blackhorse_road", R.string.station_blackhorse_road, listOf(R.string.zone_3)),
    Station("blackwall", R.string.station_blackwall, listOf(R.string.zone_2)),
    Station("bond_street", R.string.station_bond_street, listOf(R.string.zone_1)),
    Station("borough", R.string.station_borough, listOf(R.string.zone_1)),
    Station("boston_manor", R.string.station_boston_manor, listOf(R.string.zone_4)),
    Station("bounds_green", R.string.station_bounds_green, listOf(R.string.zone_3,R.string.zone_4)),
    Station("bow_church", R.string.station_bow_church, listOf(R.string.zone_2)),
    Station("bow_road", R.string.station_bow_road, listOf(R.string.zone_2)),
    Station("brent_cross", R.string.station_brent_cross, listOf(R.string.zone_3)),
    Station("brentwood", R.string.station_brentwood, listOf(R.string.zone_9)),
    Station("brixton", R.string.station_brixton, listOf(R.string.zone_2)),
    Station("brockley", R.string.station_brockley, listOf(R.string.zone_2)),
    Station("bromley_by_bow", R.string.station_bromley_by_bow, listOf(R.string.zone_2,R.string.zone_3)),
    Station("brondesbury", R.string.station_brondesbury, listOf(R.string.zone_2)),
    Station("brondesbury_park", R.string.station_brondesbury_park, listOf(R.string.zone_2)),
    Station("bruce_grove", R.string.station_bruce_grove, listOf(R.string.zone_3)),
    Station("buckhurst_hill", R.string.station_buckhurst_hill, listOf(R.string.zone_5)),
    Station("burnham", R.string.station_burnham, listOf(R.string.zone_special)),
    Station("burnt_oak", R.string.station_burnt_oak, listOf(R.string.zone_4)),
    Station("bush_hill_park", R.string.station_bush_hill_park, listOf(R.string.zone_5)),
    Station("bushey", R.string.station_bushey, listOf(R.string.zone_8)),

    // C (42)
    Station("caledonian_road", R.string.station_caledonian_road, listOf(R.string.zone_2)),
    Station("caledonian_road_and_barnsbury", R.string.station_caledonian_road_and_barnsbury, listOf(R.string.zone_2)),
    Station("cambridge_heath", R.string.station_cambridge_heath, listOf(R.string.zone_2)),
    Station("camden_road", R.string.station_camden_road, listOf(R.string.zone_2)),
    Station("camden_town", R.string.station_camden_town, listOf(R.string.zone_2)),
    Station("canada_water", R.string.station_canada_water, listOf(R.string.zone_2)),
    Station("canary_wharf", R.string.station_canary_wharf, listOf(R.string.zone_2)),
    Station("canning_town", R.string.station_canning_town, listOf(R.string.zone_2,R.string.zone_3)),
    Station("cannon_street", R.string.station_cannon_street, listOf(R.string.zone_1)),
    Station("canonbury", R.string.station_canonbury, listOf(R.string.zone_2)),
    Station("canons_park", R.string.station_canons_park, listOf(R.string.zone_5)),
    Station("carpenders_park", R.string.station_carpenders_park, listOf(R.string.zone_7)),
    Station("centrale", R.string.station_centrale, listOf(R.string.zone_special)),
    Station("chadwell_heath", R.string.station_chadwell_heath, listOf(R.string.zone_5)),
    Station("chalfont_and_latimer", R.string.station_chalfont_and_latimer, listOf(R.string.zone_8)),
    Station("chalk_farm", R.string.station_chalk_farm, listOf(R.string.zone_2)),
    Station("chancery_lane", R.string.station_chancery_lane, listOf(R.string.zone_1)),
    Station("charing_cross", R.string.station_charing_cross, listOf(R.string.zone_1)),
    Station("chesham", R.string.station_chesham, listOf(R.string.zone_9)),
    Station("cheshunt", R.string.station_cheshunt, listOf(R.string.zone_8)),
    Station("chigwell", R.string.station_chingford, listOf(R.string.zone_5)),
    Station("chiswick_park", R.string.station_chiswick_park, listOf(R.string.zone_3)),
    Station("chorleywood", R.string.station_chorleywood, listOf(R.string.zone_7)),
    Station("church_street", R.string.station_church_street, listOf(R.string.zone_special)),
    Station("clapham_common", R.string.station_clapham_common, listOf(R.string.zone_2)),
    Station("clapham_high_street", R.string.station_clapham_high_street, listOf(R.string.zone_2)),
    Station("clapham_junction", R.string.station_clapham_junction, listOf(R.string.zone_2)),
    Station("clapham_north", R.string.station_clapham_north, listOf(R.string.zone_2)),
    Station("clapham_south", R.string.station_clapham_south, listOf(R.string.zone_2, R.string.zone_3)),
    Station("clapton", R.string.station_clapton, listOf(R.string.zone_2, R.string.zone_3)),
    Station("cockfosters", R.string.station_cockfosters, listOf(R.string.zone_5)),
    Station("colindale", R.string.station_colindale, listOf(R.string.zone_4)),
    Station("colliers_wood", R.string.station_colliers_wood, listOf(R.string.zone_3)),
    Station("coombe_lane", R.string.station_coombe_lane, listOf(R.string.zone_special)),
    Station("covent_garden", R.string.station_covent_garden, listOf(R.string.zone_1)),
    Station("crossharbour", R.string.station_crossharbour, listOf(R.string.zone_2)),
    Station("crouch_hill", R.string.station_crouch_hill, listOf(R.string.zone_3)),
    Station("croxley", R.string.station_croxley, listOf(R.string.zone_7)),
    Station("crystal_palace", R.string.station_crystal_palace, listOf(R.string.zone_3, R.string.zone_4)),
    Station("custom_house", R.string.station_custom_house, listOf(R.string.zone_3)),
    Station("cutty_sark", R.string.station_cutty_sark, listOf(R.string.zone_2, R.string.zone_3)),
    Station("cyprus", R.string.station_cyprus, listOf(R.string.zone_3)),

    // D (10)
    Station("dagenham_east", R.string.station_dagenham_east, listOf(R.string.zone_6)),
    Station("dagenham_heathway", R.string.station_dagenham_heathway, listOf(R.string.zone_6)),
    Station("dalston_junction", R.string.station_dalston_junction, listOf(R.string.zone_2)),
    Station("dalston_kingsland", R.string.station_dalston_kingsland, listOf(R.string.zone_2)),
    Station("debden", R.string.station_debden, listOf(R.string.zone_6)),
    Station("denmark_hill", R.string.station_denmark_hill, listOf(R.string.zone_2)),
    Station("deptford_bridge", R.string.station_deptford_bridge, listOf(R.string.zone_2, R.string.zone_3)),
    Station("devons_road", R.string.station_devons_road, listOf(R.string.zone_2)),
    Station("dollis_hill", R.string.station_dollis_hill, listOf(R.string.zone_3)),
    Station("dundonald_road", R.string.station_dundonald_road, listOf(R.string.zone_special)),

    // E (23)
    Station("ealing_broadway", R.string.station_ealing_broadway, listOf(R.string.zone_3)),
    Station("ealing_common", R.string.station_ealing_common, listOf(R.string.zone_3)),
    Station("earls_court", R.string.station_earls_court, listOf(R.string.zone_1, R.string.zone_2)),
    Station("east_acton", R.string.station_east_acton, listOf(R.string.zone_2)),
    Station("east_croydon", R.string.station_east_croydon, listOf(R.string.zone_special)),
    Station("east_finchley", R.string.station_east_finchley, listOf(R.string.zone_3)),
    Station("east_ham", R.string.station_east_ham, listOf(R.string.zone_3, R.string.zone_4)),
    Station("east_india", R.string.station_east_india, listOf(R.string.zone_2, R.string.zone_3)),
    Station("east_putney", R.string.station_east_putney, listOf(R.string.zone_2, R.string.zone_3)),
    Station("eastcote", R.string.station_eastcote, listOf(R.string.zone_5)),
    Station("edgware", R.string.station_edgware, listOf(R.string.zone_5)),
    Station("edgware_road", R.string.station_edgware_road, listOf(R.string.zone_1)),
    Station("edmonton_green", R.string.station_edmonton_green, listOf(R.string.zone_4)),
    Station("elephant_and_castle", R.string.station_elephant_and_castle, listOf(R.string.zone_1, R.string.zone_2)),
    Station("elmers_end", R.string.station_elmers_end, listOf(R.string.zone_special)),
    Station("elm_park", R.string.station_elm_park, listOf(R.string.zone_6)),
    Station("elverson_road", R.string.station_elverson_road, listOf(R.string.zone_2, R.string.zone_3)),
    Station("embankment", R.string.station_embankment, listOf(R.string.zone_1)),
    Station("emerson_park", R.string.station_emerson_park, listOf(R.string.zone_6)),
    Station("enfield_town", R.string.station_enfield_town, listOf(R.string.zone_5)),
    Station("epping", R.string.station_epping, listOf(R.string.zone_6)),
    Station("euston", R.string.station_euston, listOf(R.string.zone_1)),
    Station("euston_square", R.string.station_euston_square, listOf(R.string.zone_1)),

    // F (10)
    Station("fairlop", R.string.station_fairlop, listOf(R.string.zone_4)),
    Station("farringdon", R.string.station_farringdon, listOf(R.string.zone_1)),
    Station("fieldway", R.string.station_fieldway, listOf(R.string.zone_special)),
    Station("finchley_central", R.string.station_finchley_central, listOf(R.string.zone_4)),
    Station("finchley_road", R.string.station_finchley_road, listOf(R.string.zone_2)),
    Station("finchley_road_and_frognal", R.string.station_finchley_road_and_frognal, listOf(R.string.zone_2)),
    Station("finsbury_park", R.string.station_finsbury_park, listOf(R.string.zone_2)),
    Station("forest_gate", R.string.station_forest_gate, listOf(R.string.zone_3)),
    Station("forest_Hill", R.string.station_forest_hill, listOf(R.string.zone_3)),
    Station("fulham_broadway", R.string.station_fulham_broadway, listOf(R.string.zone_2)),

    // G (18)
    Station("gallions_reach", R.string.station_gallions_reach, listOf(R.string.zone_3)),
    Station("gants_hill", R.string.station_gants_hill, listOf(R.string.zone_4)),
    Station("george_street", R.string.station_george_street, listOf(R.string.zone_special)),
    Station("gidea_park", R.string.station_gidea_park, listOf(R.string.zone_6)),
    Station("gloucester_road", R.string.station_gloucester_road, listOf(R.string.zone_1)),
    Station("golders_green", R.string.station_golders_green, listOf(R.string.zone_3)),
    Station("goldhawk_road", R.string.station_goldhawk_road, listOf(R.string.zone_2)),
    Station("goodge_street", R.string.station_goodge_street, listOf(R.string.zone_1)),
    Station("goodmayes", R.string.station_goodmayes, listOf(R.string.zone_4)),
    Station("gospeal_oak", R.string.station_gospel_oak, listOf(R.string.zone_2)),
    Station("grange_hill", R.string.station_grange_hill, listOf(R.string.zone_4)),
    Station("gravel_hill", R.string.station_gravel_hill, listOf(R.string.zone_special)),
    Station("great_portland_street", R.string.station_great_portland_street, listOf(R.string.zone_1)),
    Station("green_park", R.string.station_green_park, listOf(R.string.zone_1)),
    Station("greenford", R.string.station_greenford, listOf(R.string.zone_4)),
    Station("greenwich", R.string.station_greenwich, listOf(R.string.zone_2, R.string.zone_3)),
    Station("greenwich", R.string.station_greenwich_peninsula, listOf(R.string.zone_special)),
    Station("gunnersbury", R.string.station_gunnersbury, listOf(R.string.zone_3)),

    // H (42)
    Station("hackney_central", R.string.station_hackney_central, listOf(R.string.zone_2)),
    Station("hackney_downs", R.string.station_hackney_downs, listOf(R.string.zone_2)),
    Station("hackney_wick", R.string.station_hackney_wick, listOf(R.string.zone_2)),
    Station("haggerston", R.string.station_haggerston, listOf(R.string.zone_2)),
    Station("hainault", R.string.station_hainault, listOf(R.string.zone_4)),
    Station("hammersmith", R.string.station_hammersmith, listOf(R.string.zone_2)),
    Station("hampstead", R.string.station_hampstead, listOf(R.string.zone_2, R.string.zone_3)),
    Station("hampstead_heath", R.string.station_hampstead_heath, listOf(R.string.zone_2)),
    Station("hanger_lane", R.string.station_hanger_lane, listOf(R.string.zone_3)),
    Station("hanwell", R.string.station_hanwell, listOf(R.string.zone_4)),
    Station("harlesden", R.string.station_harlesden, listOf(R.string.zone_3)),
    Station("harold_wood", R.string.station_harold_wood, listOf(R.string.zone_6)),
    Station("harringay_green_lanes", R.string.station_harringay_green_lanes, listOf(R.string.zone_3)),
    Station("harrington_road", R.string.station_harrington_road, listOf(R.string.zone_special)),
    Station("harrow_and_wealdstone", R.string.station_harrow_and_wealdstone, listOf(R.string.zone_5)),
    Station("harrow_on_the_hill", R.string.station_harrow_on_the_hill, listOf(R.string.zone_5)),
    Station("hatch_end", R.string.station_hatch_end, listOf(R.string.zone_6)),
    Station("hatton_cross", R.string.station_hatton_cross, listOf(R.string.zone_5, R.string.zone_6)),
    Station("hayes_and_harlington", R.string.station_hayes_and_harlington, listOf(R.string.zone_6)),
    Station("headstone_lane", R.string.station_headstone_lane, listOf(R.string.zone_6)),
    Station("heathrow_terminals_2_and_3", R.string.station_heathrow_terminals_2_and_3, listOf(R.string.zone_6_special)),
    Station("heathrow_terminal_4", R.string.station_heathrow_terminal_4, listOf(R.string.zone_6_special)),
    Station("heathrow_terminal_5", R.string.station_heathrow_terminal_5, listOf(R.string.zone_6_special)),
    Station("hendon_central", R.string.station_hendon_central, listOf(R.string.zone_3, R.string.zone_4)),
    Station("heron_quays", R.string.station_heron_quays, listOf(R.string.zone_2)),
    Station("high_barnet", R.string.station_high_barnet, listOf(R.string.zone_5)),
    Station("high_street_kensington", R.string.station_high_street_kensington, listOf(R.string.zone_1)),
    Station("highams_park", R.string.station_highams_park, listOf(R.string.zone_4)),
    Station("highbury_and_islington", R.string.station_highbury_and_islington, listOf(R.string.zone_2)),
    Station("highgate", R.string.station_highgate, listOf(R.string.zone_3)),
    Station("hillingdon", R.string.station_hillingdon, listOf(R.string.zone_6)),
    Station("holborn", R.string.station_holborn, listOf(R.string.zone_1)),
    Station("holland_park", R.string.station_holland_park, listOf(R.string.zone_1)),
    Station("holloway_road", R.string.station_holloway_road, listOf(R.string.zone_2)),
    Station("homerton", R.string.station_homerton, listOf(R.string.zone_2)),
    Station("honor_oak_park", R.string.station_honor_oak_park, listOf(R.string.zone_3)),
    Station("hornchurch", R.string.station_hornchurch, listOf(R.string.zone_6)),
    Station("hounslow_central", R.string.station_hounslow_central, listOf(R.string.zone_4)),
    Station("hounslow_east", R.string.station_hounslow_east, listOf(R.string.zone_4)),
    Station("hounslow_west", R.string.station_hounslow_west, listOf(R.string.zone_5)),
    Station("hoxton", R.string.station_hoxton, listOf(R.string.zone_1, R.string.zone_2)),
    Station("hyde_park_corner", R.string.station_hyde_park_corner, listOf(R.string.zone_1)),

    // I (5)
    Station("ickenham", R.string.station_ickenham,listOf(R.string.zone_6)),
    Station("ilford", R.string.station_ilford,listOf(R.string.zone_4)),
    Station("imperial_wharf", R.string.station_imperial_wharf,listOf(R.string.zone_2)),
    Station("island_gardens", R.string.station_island_gardens,listOf(R.string.zone_2)),
    Station("iver", R.string.station_iver,listOf(R.string.zone_special)),

    // K (16)
    Station("kennington", R.string.station_kennington, listOf(R.string.zone_1, R.string.zone_2)),
    Station("kensal_green", R.string.station_kensal_green, listOf(R.string.zone_2)),
    Station("kensal_rise", R.string.station_kensal_rise, listOf(R.string.zone_2)),
    Station("kensington_olympia", R.string.station_kensington_olympia, listOf(R.string.zone_2)),
    Station("kentish_town", R.string.station_kentish_town, listOf(R.string.zone_2)),
    Station("kentish_town_west", R.string.station_kentish_town_west, listOf(R.string.zone_2)),
    Station("kenton", R.string.station_kenton, listOf(R.string.zone_4)),
    Station("kew_gardens", R.string.station_kew_gardens, listOf(R.string.zone_3, R.string.zone_4)),
    Station("kilburn", R.string.station_kilburn, listOf(R.string.zone_2)),
    Station("kilburn_high_road", R.string.station_kilburn_high_road, listOf(R.string.zone_2)),
    Station("kilburn_park", R.string.station_kilburn_park, listOf(R.string.zone_2)),
    Station("king_george_v", R.string.station_king_george_v, listOf(R.string.zone_3)),
    Station("king_henrys_drive", R.string.station_king_henrys_drive, listOf(R.string.zone_special)),
    Station("kings_cross_st_pancras", R.string.station_kings_cross_st_pancras, listOf(R.string.zone_1)),
    Station("kingsbury", R.string.station_kingsbury, listOf(R.string.zone_4)),
    Station("knightsbridge", R.string.station_knightsbridge, listOf(R.string.zone_1)),

    // L (10)
    Station("ladbroke_grove", R.string.station_ladbroke_grove, listOf(R.string.zone_2)),
    Station("lambeth_north", R.string.station_lambeth_north, listOf(R.string.zone_1)),
    Station("lancaster_gate", R.string.station_lancaster_gate, listOf(R.string.zone_1)),
    Station("langdon_park", R.string.station_langdon_park, listOf(R.string.zone_2)),
    Station("langley", R.string.station_langley, listOf(R.string.zone_special)),
    Station("latimer_road", R.string.station_latimer_road, listOf(R.string.zone_2)),
    Station("lebanon_road", R.string.station_lebanon_road, listOf(R.string.zone_special)),
    Station("leicester_square", R.string.station_leicester_square, listOf(R.string.zone_1)),
    Station("lewisham", R.string.station_lewisham, listOf(R.string.zone_2, R.string.zone_3)),
    Station("leyton", R.string.station_leyton, listOf(R.string.zone_3)),
    Station("leyton_midland_road", R.string.station_leyton_midland_road, listOf(R.string.zone_3)),
    Station("leytonstone", R.string.station_leytonstone, listOf(R.string.zone_3, R.string.zone_4)),
    Station("leytonstone_high_road", R.string.station_leytonstone_high_road, listOf(R.string.zone_3)),
    Station("limehouse", R.string.station_limehouse, listOf(R.string.zone_2)),
    Station("liverpool_street", R.string.station_liverpool_street, listOf(R.string.zone_1)),
    Station("lloyd_park", R.string.station_lloyd_park, listOf(R.string.zone_special)),
    Station("london_bridge", R.string.station_london_bridge, listOf(R.string.zone_1)),
    Station("london_city_airport", R.string.station_london_city_airport, listOf(R.string.zone_3)),
    Station("london_fields", R.string.station_london_fields, listOf(R.string.zone_2)),
    Station("loughton", R.string.station_loughton, listOf(R.string.zone_6)),

    // M (20)
    Station("maida_vale", R.string.station_maida_vale, listOf(R.string.zone_2)),
    Station("maidenhead", R.string.station_maidenhead, listOf(R.string.zone_special)),
    Station("manor_house", R.string.station_manor_house, listOf(R.string.zone_2, R.string.zone_3)),
    Station("manor_park", R.string.station_manor_park, listOf(R.string.zone_3, R.string.zone_4)),
    Station("mansion_house", R.string.station_mansion_house, listOf(R.string.zone_1)),
    Station("marble_arch", R.string.station_marble_arch, listOf(R.string.zone_1)),
    Station("maryland", R.string.station_maryland, listOf(R.string.zone_3)),
    Station("marylebone", R.string.station_marylebone, listOf(R.string.zone_1)),
    Station("merton_park", R.string.station_merton_park, listOf(R.string.zone_special)),
    Station("mile_end", R.string.station_mile_end, listOf(R.string.zone_2)),
    Station("mill_hill_east", R.string.station_mill_hill_east, listOf(R.string.zone_4)),
    Station("mitcham", R.string.station_mitcham, listOf(R.string.zone_special)),
    Station("mitcham_junction", R.string.station_mitcham_junction, listOf(R.string.zone_special)),
    Station("monument", R.string.station_monument, listOf(R.string.zone_1)),
    Station("moor_park", R.string.station_moor_park, listOf(R.string.zone_6, R.string.zone_7)),
    Station("moorgate", R.string.station_moorgate, listOf(R.string.zone_1)),
    Station("morden", R.string.station_morden, listOf(R.string.zone_4)),
    Station("morden_road", R.string.station_morden_road, listOf(R.string.zone_special)),
    Station("mornington_crescent", R.string.station_mornington_crescent, listOf(R.string.zone_2)),
    Station("mudchute", R.string.station_mudchute, listOf(R.string.zone_2)),

    // N (18)
    Station("neasden", R.string.station_neasden, listOf(R.string.zone_3)),
    Station("new_addington", R.string.station_new_addington, listOf(R.string.zone_special)),
    Station("new_cross", R.string.station_new_cross, listOf(R.string.zone_2)),
    Station("new_cross_gate", R.string.station_new_cross_gate, listOf(R.string.zone_2)),
    Station("newbury_park", R.string.station_newbury_park, listOf(R.string.zone_4)),
    Station("nine_elms", R.string.station_nine_elms, listOf(R.string.zone_1)),
    Station("north_acton", R.string.station_north_acton, listOf(R.string.zone_2, R.string.zone_3)),
    Station("north_ealing", R.string.station_north_ealing, listOf(R.string.zone_3)),
    Station("north_greenwich", R.string.station_north_greenwich, listOf(R.string.zone_2, R.string.zone_3)),
    Station("north_harrow", R.string.station_north_harrow, listOf(R.string.zone_5)),
    Station("north_wembley", R.string.station_north_wembley, listOf(R.string.zone_4)),
    Station("northfields", R.string.station_northfields, listOf(R.string.zone_3)),
    Station("northolt", R.string.station_northolt, listOf(R.string.zone_5)),
    Station("northwick_park", R.string.station_northwick_park, listOf(R.string.zone_4)),
    Station("northwood", R.string.station_northwood, listOf(R.string.zone_6)),
    Station("northwood_hills", R.string.station_northwood_hills, listOf(R.string.zone_6)),
    Station("norwood_junction", R.string.station_norwood_junction, listOf(R.string.zone_4)),
    Station("notting_hill_gate", R.string.station_notting_hill_gate, listOf(R.string.zone_1, R.string.zone_2)),

    // O (5)
    Station("oakwood", R.string.station_oakwood, listOf(R.string.zone_5)),
    Station("old_street", R.string.station_old_street, listOf(R.string.zone_1)),
    Station("osterley", R.string.station_osterley, listOf(R.string.zone_4)),
    Station("oval", R.string.station_oval, listOf(R.string.zone_2)),
    Station("oxford_circus", R.string.station_oxford_circus, listOf(R.string.zone_1)),

    // P (17)
    Station("paddington", R.string.station_paddington, listOf(R.string.zone_1)),
    Station("park_royal", R.string.station_park_royal, listOf(R.string.zone_3)),
    Station("parsons_green", R.string.station_parsons_green, listOf(R.string.zone_2)),
    Station("peckham_rye", R.string.station_peckham_rye, listOf(R.string.zone_2)),
    Station("penge_west", R.string.station_penge_west, listOf(R.string.zone_4)),
    Station("perivale", R.string.station_perivale, listOf(R.string.zone_4)),
    Station("phipps_bridge", R.string.station_phipps_bridge, listOf(R.string.zone_special)),
    Station("piccadilly_circus", R.string.station_piccadilly_circus, listOf(R.string.zone_1)),
    Station("pimlico", R.string.station_pimlico, listOf(R.string.zone_1)),
    Station("pinner", R.string.station_pinner, listOf(R.string.zone_5)),
    Station("plaistow", R.string.station_plaistow, listOf(R.string.zone_3)),
    Station("pontoon_dock", R.string.station_pontoon_dock, listOf(R.string.zone_3)),
    Station("poplar", R.string.station_poplar, listOf(R.string.zone_2)),
    Station("preston_road", R.string.station_preston_road, listOf(R.string.zone_4)),
    Station("prince_regent", R.string.station_prince_regent, listOf(R.string.zone_3)),
    Station("pudding_mill_lane", R.string.station_pudding_mill_lane, listOf(R.string.zone_2, R.string.zone_3)),
    Station("putney_bridge", R.string.station_putney_bridge, listOf(R.string.zone_2)),

    // Q (4)
    Station("queens_park", R.string.station_queens_park, listOf(R.string.zone_2)),
    Station("queens_road_peckham", R.string.station_queens_road_peckham, listOf(R.string.zone_2)),
    Station("queensbury", R.string.station_queensbury, listOf(R.string.zone_4)),
    Station("queensway", R.string.station_queensway, listOf(R.string.zone_1)),

    // R (20)
    Station("ravenscourt_park", R.string.station_ravenscourt_park, listOf(R.string.zone_2)),
    Station("rayners_lane", R.string.station_rayners_lane, listOf(R.string.zone_5)),
    Station("reading", R.string.station_reading, listOf(R.string.zone_special)),
    Station("rectory_road", R.string.station_rectory_road, listOf(R.string.zone_2)),
    Station("redbridge", R.string.station_redbridge, listOf(R.string.zone_4)),
    Station("reeves_corner", R.string.station_reeves_corner, listOf(R.string.zone_special)),
    Station("regents_park", R.string.station_regents_park, listOf(R.string.zone_1)),
    Station("richmond", R.string.station_richmond, listOf(R.string.zone_4)),
    Station("rickmansworth", R.string.station_rickmansworth, listOf(R.string.zone_7)),
    Station("roding_valley", R.string.station_roding_valley, listOf(R.string.zone_4)),
    Station("romford", R.string.station_romford, listOf(R.string.zone_6)),
    Station("rotherhithe", R.string.station_rotherhithe, listOf(R.string.zone_2)),
    Station("royal_albert", R.string.station_royal_albert, listOf(R.string.zone_3)),
    Station("royal_docks", R.string.station_royal_docks, listOf(R.string.zone_special)),
    Station("royal_oak", R.string.station_royal_oak, listOf(R.string.zone_2)),
    Station("royal_victoria", R.string.station_royal_victoria, listOf(R.string.zone_3)),
    Station("ruislip", R.string.station_ruislip, listOf(R.string.zone_6)),
    Station("ruislip_gardens", R.string.station_ruislip_gardens, listOf(R.string.zone_5)),
    Station("ruislip_manor", R.string.station_ruislip_manor, listOf(R.string.zone_6)),
    Station("russell_square", R.string.station_russell_square, listOf(R.string.zone_1)),

    // S (48)
    Station("st_james_street", R.string.station_st_james_street, listOf(R.string.zone_3)),
    Station("st_james_park", R.string.station_st_james_park, listOf(R.string.zone_1)),
    Station("st_johns_wood", R.string.station_st_johns_wood, listOf(R.string.zone_2)),
    Station("st_pauls", R.string.station_st_pauls, listOf(R.string.zone_1)),
    Station("sandilands", R.string.station_sandilands, listOf(R.string.zone_special)),
    Station("seven_kings", R.string.station_seven_kings, listOf(R.string.zone_4)),
    Station("seven_sisters", R.string.station_seven_sisters, listOf(R.string.zone_3)),
    Station("shadwell", R.string.station_shadwell, listOf(R.string.zone_2)),
    Station("shenfield", R.string.station_shenfield, listOf(R.string.zone_b)),
    Station("shepherds_bush", R.string.station_shepherds_bush, listOf(R.string.zone_2)),
    Station("shepherds_bush_market", R.string.station_shepherds_bush_market, listOf(R.string.zone_2)),
    Station("shoreditch_high_street", R.string.station_shoreditch_high_street, listOf(R.string.zone_1)),
    Station("silver_street", R.string.station_silver_street, listOf(R.string.zone_4)),
    Station("sloane_square", R.string.station_sloane_square, listOf(R.string.zone_1)),
    Station("slough", R.string.station_slough, listOf(R.string.zone_special)),
    Station("snaresbrook", R.string.station_snaresbrook, listOf(R.string.zone_4)),
    Station("south_acton", R.string.station_south_acton, listOf(R.string.zone_3)),
    Station("south_ealing", R.string.station_south_ealing, listOf(R.string.zone_3)),
    Station("south_hampstead", R.string.station_south_hampstead, listOf(R.string.zone_2)),
    Station("south_harrow", R.string.station_south_harrow, listOf(R.string.zone_5)),
    Station("south_kensington", R.string.station_south_kensington, listOf(R.string.zone_1)),
    Station("south_kenton", R.string.station_south_kenton, listOf(R.string.zone_4)),
    Station("south_quay", R.string.station_south_quay, listOf(R.string.zone_2)),
    Station("south_ruislip", R.string.station_south_ruislip, listOf(R.string.zone_5)),
    Station("south_tottenham", R.string.station_south_tottenham, listOf(R.string.zone_3)),
    Station("south_wimbledon", R.string.station_south_wimbledon, listOf(R.string.zone_3, R.string.zone_4)),
    Station("south_woodford", R.string.station_south_woodford, listOf(R.string.zone_4)),
    Station("southall", R.string.station_southall, listOf(R.string.zone_4)),
    Station("southbury", R.string.station_southbury, listOf(R.string.zone_5)),
    Station("southfields", R.string.station_southfields, listOf(R.string.zone_3)),
    Station("southgate", R.string.station_southgate, listOf(R.string.zone_4)),
    Station("southwark", R.string.station_southwark, listOf(R.string.zone_1)),
    Station("stamford_brook", R.string.station_stamford_brook, listOf(R.string.zone_2)),
    Station("stamford_hill", R.string.station_stamford_hill, listOf(R.string.zone_3)),
    Station("stanmore", R.string.station_stanmore, listOf(R.string.zone_5)),
    Station("star_lane", R.string.station_star_lane, listOf(R.string.zone_2, R.string.zone_3)),
    Station("stepney_green", R.string.station_stepney_green, listOf(R.string.zone_2)),
    Station("stockwell", R.string.station_stockwell, listOf(R.string.zone_2)),
    Station("stoke_newington", R.string.station_stoke_newington, listOf(R.string.zone_2)),
    Station("stonebridge_park", R.string.station_stonebridge_park, listOf(R.string.zone_3)),
    Station("stratford", R.string.station_stratford, listOf(R.string.zone_2, R.string.zone_3)),
    Station("stratford_high_street", R.string.station_stratford_high_street, listOf(R.string.zone_2, R.string.zone_3)),
    Station("stratford_international", R.string.station_stratford_international, listOf(R.string.zone_2, R.string.zone_3)),
    Station("sudbury_town", R.string.station_sudbury_town, listOf(R.string.zone_4)),
    Station("sudbury_hill", R.string.station_sudbury_hill, listOf(R.string.zone_4)),
    Station("surrey_quays", R.string.station_surrey_quays, listOf(R.string.zone_2)),
    Station("swiss_cottage", R.string.station_swiss_cottage, listOf(R.string.zone_2)),
    Station("sydenham", R.string.station_sydenham, listOf(R.string.zone_3)),

    // T (17)
    Station("taplow", R.string.station_taplow, listOf(R.string.zone_special)),
    Station("temple", R.string.station_temple, listOf(R.string.zone_1)),
    Station("theobalds_grove", R.string.station_theobalds_grove, listOf(R.string.zone_7)),
    Station("therapia_lane", R.string.station_therapia_lane, listOf(R.string.zone_special)),
    Station("theydon_bois", R.string.station_theydon_bois, listOf(R.string.zone_6)),
    Station("tooting_bec", R.string.station_tooting_bec, listOf(R.string.zone_3)),
    Station("tooting_broadway", R.string.station_tooting_broadway, listOf(R.string.zone_3)),
    Station("tottenham_court_road", R.string.station_tottenham_court_road, listOf(R.string.zone_1)),
    Station("tottenham_hale", R.string.station_tottenham_hale, listOf(R.string.zone_3)),
    Station("totteridge_whetstone", R.string.station_totteridge_whetstone, listOf(R.string.zone_4)),
    Station("tower_gateway", R.string.station_tower_gateway, listOf(R.string.zone_1)),
    Station("tower_hill", R.string.station_tower_hill, listOf(R.string.zone_1)),
    Station("tufnell_park", R.string.station_tufnell_park, listOf(R.string.zone_2)),
    Station("turkey_street", R.string.station_turkey_street, listOf(R.string.zone_6)),
    Station("turnham_green", R.string.station_turnham_green, listOf(R.string.zone_2, R.string.zone_3)),
    Station("turnpike_lane", R.string.station_turnpike_lane, listOf(R.string.zone_3)),
    Station("twyford", R.string.station_twyford, listOf(R.string.zone_special)),

    // U (6)
    Station("upminster", R.string.station_upminster,listOf(R.string.zone_6)),
    Station("upminster_bridge", R.string.station_upminster_bridge,listOf(R.string.zone_6)),
    Station("upney", R.string.station_upney,listOf(R.string.zone_4)),
    Station("upper_holloway", R.string.station_upper_holloway,listOf(R.string.zone_2)),
    Station("upton_park", R.string.station_upton_park,listOf(R.string.zone_3)),
    Station("uxbridge", R.string.station_uxbridge,listOf(R.string.zone_6)),

    // V (2)
    Station("vauxhall", R.string.station_vauxhall, listOf(R.string.zone_1, R.string.zone_2)),
    Station("victoria", R.string.station_victoria, listOf(R.string.zone_1)),

    // W (49)
    Station("waddon_marsh", R.string.station_waddon_marsh, listOf(R.string.zone_special)),
    Station("walthamstow_centralwalthamstow_central", R.string.station_walthamstow_central, listOf(R.string.zone_3)),
    Station("walthamstow_queens_road", R.string.station_walthamstow_queens_road, listOf(R.string.zone_3)),
    Station("wandle_park", R.string.station_wandle_park, listOf(R.string.zone_special)),
    Station("wandsworth_road", R.string.station_wandsworth_road, listOf(R.string.zone_2)),
    Station("wanstead", R.string.station_wanstead, listOf(R.string.zone_4)),
    Station("wanstead_park", R.string.station_wanstead_park, listOf(R.string.zone_3)),
    Station("wapping", R.string.station_wapping, listOf(R.string.zone_2)),
    Station("warren_streetwarren_street", R.string.station_warren_street, listOf(R.string.zone_1)),
    Station("warwick_avenue", R.string.station_warwick_avenue, listOf(R.string.zone_2)),
    Station("waterloo", R.string.station_waterloo, listOf(R.string.zone_1)),
    Station("watford", R.string.station_watford, listOf(R.string.zone_7)),
    Station("watford_high_street", R.string.station_watford_high_street, listOf(R.string.zone_8)),
    Station("watford_junction", R.string.station_watford_junction, listOf(R.string.zone_a)),
    Station("wellesley_road", R.string.station_wellesley_road, listOf(R.string.zone_special)),
    Station("wembley_central", R.string.station_wembley_central, listOf(R.string.zone_4)),
    Station("wembley_park", R.string.station_wembley_park, listOf(R.string.zone_4)),
    Station("west_acton", R.string.station_west_acton, listOf(R.string.zone_3)),
    Station("west_brompton", R.string.station_west_brompton, listOf(R.string.zone_2)),
    Station("west_croydon_underground", R.string.station_west_croydon, listOf(R.string.zone_5)),
    Station("west_croydon_tram", R.string.station_west_croydon, listOf(R.string.zone_special)),
    Station("west_drayton", R.string.station_west_drayton, listOf(R.string.zone_6)),
    Station("west_ealing", R.string.station_west_ealing, listOf(R.string.zone_3)),
    Station("west_finchley", R.string.station_west_finchley, listOf(R.string.zone_4)),
    Station("west_ham", R.string.station_west_ham, listOf(R.string.zone_2, R.string.zone_3)),
    Station("west_hampstead", R.string.station_west_hampstead, listOf(R.string.zone_2)),
    Station("west_harrow", R.string.station_west_harrow, listOf(R.string.zone_5)),
    Station("west_india_quay", R.string.station_west_india_quay, listOf(R.string.zone_2)),
    Station("west_kensington", R.string.station_west_kensington, listOf(R.string.zone_2)),
    Station("west_ruislip", R.string.station_west_ruislip, listOf(R.string.zone_6)),
    Station("west_silvertown", R.string.station_west_silvertown, listOf(R.string.zone_3)),
    Station("westbourne_park", R.string.station_westbourne_park, listOf(R.string.zone_2)),
    Station("westferry", R.string.station_westferry, listOf(R.string.zone_2)),
    Station("westminster", R.string.station_westminster, listOf(R.string.zone_1)),
    Station("white_city", R.string.station_white_city, listOf(R.string.zone_2)),
    Station("white_hart_lane", R.string.station_white_hart_lane, listOf(R.string.zone_3)),
    Station("whitechapel", R.string.station_whitechapel, listOf(R.string.zone_2)),
    Station("willesden_green", R.string.station_willesden_green, listOf(R.string.zone_2, R.string.zone_3)),
    Station("willesden_junction", R.string.station_willesden_junction, listOf(R.string.zone_2, R.string.zone_3)),
    Station("wimbledon_underground", R.string.station_wimbledon, listOf(R.string.zone_3)),
    Station("wimbledon_tram", R.string.station_wimbledon, listOf(R.string.zone_special)),
    Station("wimbledon_park", R.string.station_wimbledon_park, listOf(R.string.zone_3)),
    Station("wood_green", R.string.station_wood_green, listOf(R.string.zone_3)),
    Station("wood_lane", R.string.station_wood_lane, listOf(R.string.zone_2)),
    Station("wood_street", R.string.station_wood_street, listOf(R.string.zone_4)),
    Station("woodford", R.string.station_woodford, listOf(R.string.zone_4)),
    Station("woodgrange_park", R.string.station_woodgrange_park, listOf(R.string.zone_3, R.string.zone_4)),
    Station("woodside", R.string.station_woodside, listOf(R.string.zone_special)),
    Station("woodside_park", R.string.station_woodside_park, listOf(R.string.zone_4)),
    Station("woolwich", R.string.station_woolwich, listOf(R.string.zone_4)),
    Station("woolwich_arsenal", R.string.station_woolwich_arsenal, listOf(R.string.zone_4))
)
